server:
  port: 8081
spring:
  application:
    #应用名称,可以自定义
    name: user-portrait-system
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  type-aliases-package: com.java.userportraitsystem.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启驼峰功能

pagehelper:
  helperDialect: mysql # 配置数据库连接方式
  reasonable: true # 分页合理化参数,默认值为false,参数设置为true时,当pageNum<=0,查询第一页数据,当pageNum>总页数时,会查询最后一页。当使用默认值时,会根据参数进行查询
  defaultCount: true # 分页插件默认参数支持 default-count 形式,自定义扩展的参数,必须大小写一致
  support-methods-arguments: true # 支持通过Mapper接口的参数来传递分页参数,分页插件会从查询方法的参数值中,自动根据上面 params 配置的 字段中取值,查找到合适的值时就会自动分页
  params: count==countSql # 设置当前页记录条数,比如,最后一页只有三条数据,此时count为3
  page-size-zero: true # 默认值为false,当设置参数为true时,如果pageSize=0就会查询全部结果(即没有执行分页查询,但返回结果仍为Page类型)