server:
  port: 8081
spring:
  application:
    #应用名称,可以自定义
    name: learn-mybatis
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  type-aliases-package: com.java.learnmybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

